### ISSUE TITLE
Passcode & TouchID link?

### ISSUE THREAD

**Issue by Sandi89** [phynet/iOS-URL-Schemes#1]
Hi,

Thank you for creating and maintaining this list. One thing I was not able to find is the URL for passcode & touchId settings screen? Is is possible at all to open that screen from titanium or IOS blocks it somehow?

**Comment by phynet** [comment]
Hello @Sandi89 
You can open Touch ID option with 
`UIApplication.shared.openURL(NSURL(string:"App-Prefs:root=TOUCHID_PASSCODE")! as URL)`

or 

`UIApplication.shared.open(URL(string:"App-prefs:root=General&path=TOUCHID_PASSCODE")!)`
