### ISSUE TITLE
NOTIFICATIONS_ID not opening anymore?

### ISSUE THREAD

**Issue by nxz91** [phynet/iOS-URL-Schemes#10]
Hi everyone,

I just updated to 11.4.1 and now `App-prefs:root=NOTIFICATIONS_ID` only brings me to the settings root. Are you getting a similar behavior or is it my fault?

Thanks!
Leonard

**Comment by phynet** [comment]
Hi @nxz91 since iOS 11, we cannot longer use url schemes to open any of the general preferences. This includes notification, keyboard, mobile data, etc.

**Comment by nxz91** [comment]
Hm, no I was trying to get to the push notification settings of my own app...

**Comment by nxz91** [comment]
This worked before

**Comment by phynet** [comment]
Sorry for the late update. I can open my app's settings. But not exactly the notification one....I think this is due to the update as you say. Sadly I can't dig deeper into this issue. 😭
