### ISSUE TITLE
how can i open settings from today widget?

### ISSUE THREAD

**Issue by vosho** [phynet/iOS-URL-Schemes#2]
I got error msg:
[_NCWidgetExtensionContext openURL:completionHandler:]_block_invoke failed: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"
however i'v added URL 'prefs' into info.plist extension project
Could you help with this?

**Comment by phynet** [comment]
@StevenWung  Apparently Apple blocked that functionality, from widget to settings. I haven't tested it yet, but did you try with ```UIApplication.shared.open(URL(string:UIApplicationOpenSettingsURLString)!)``` ?
