### ISSUE TITLE
iOS 11: iPhone Storage

### ISSUE THREAD

**Issue by Shugabuga** [phynet/iOS-URL-Schemes#3]
iOS 11 separates the iPhone and iCloud storage into different tabs. The following enters iCloud storage:

`App-prefs:root=CASTLE&path=STORAGE_AND_BACKUP`

What is the URL scheme for `iPhone Storage`?

**Comment by snowfrz** [comment]
I imagine it starts with `App-prefs:root=General&path=` as it is under `Settings > General`, but I don't know exactly what it is.

**Comment by phynet** [comment]
Hello @Sn0wCh1ld  and @Shugabuga since iOS 11 is still in beta state, it's difficult to find a concrete route to iPhone Storage or anything new. I have not played yet with Xcode 9 / iOS 11. But if you find anything useful, feel free to post it and I will try it out and add it to colaborations in main page 😄

**Comment by Shugabuga** [comment]
Okay. I am also going to leave this method of testing URL schemes without any extra apps:

1) Make a QR code with the text being the URL scheme
2) Slightly press on the image preview (3D Touch) and swipe up to reveal options.
3) Tap `Open in “Settings”`

**Comment by openingax** [comment]
And what is the URL sceme for `Wi-Fi settings` in iOS 11?

**Comment by Shugabuga** [comment]
@xieliying `prefs:root=WIFI` / `App-prefs:root=WIFI` doesn't work?

**Comment by serhii-londar** [comment]
@Shugabuga `App-prefs:root=WIFI ` do not works anymore in iOS 11.

**Comment by DineshKachhot** [comment]
@phynet any update on it ?

**Comment by sridharreddy123** [comment]
Hi Team, Any update on this? IOS 11 not working :( Please let us know the update on this.
Thank you!

**Comment by vneethareddy** [comment]
I am trying to open Workday  with urlscheme as workday://
its not working. Can someone helps me to get workday Ios urlscheme.

I am getting below error..
.canOpenURL: failed for URL: "workday://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)

**Comment by phynet** [comment]
Sorry, but these schemes aren't working since iOS 11, when the shortcuts app appeared :/
