### ISSUE TITLE
Settings opens in simulator but not in device iOS 11

### ISSUE THREAD

**Issue by InderKumarRathore** [phynet/iOS-URL-Schemes#5]
"App-prefs:root=General&path=Keyboard"

This opens the keyboard settings in simulator but only opens the settings app in device.

Also I have removed the URL schemes of **prefes** and it still works in simulator but doesn't work in device.

**Comment by phynet** [comment]
Hello @InderKumarRathore this sound strange, but remember that iOS 11 is still in Beta version. So, let's wait and see what are the changes in the new version when it came out officially....right now this is just toy playing I believe...we still don't know if the API for schemes will change or not... 😞

**Comment by ileadall42** [comment]
SO,the ios 11 will not support the URL schemes?

**Comment by phynet** [comment]
Not yet...apparently they've change once more the string to refer any URL scheme :/   
I'll be testing and if I find any update about this I will post it. Also, if anyone find any info about this changes, don't hesitate and share it 😄

**Comment by sridharreddy123** [comment]
Hi Team, Any update on this? IOS 11 not working :( Please let us know the update on this.
Thank you!
