### ISSUE TITLE
Locations Scheme not working IOS 11

### ISSUE THREAD

**Issue by ulaserdegor** [phynet/iOS-URL-Schemes#7]
Hi,
This url worked before. -> App-Prefs: root = Privacy & path = LOCATION
But on iOS 11 devices, only the settings screen is opened. Can you find a solution?

**Comment by phynet** [comment]
Yes, as commented in other threads, the schemes aren't working in iOS 11 anymore. We are trying to see if Apple somehow allows it...

**Comment by haiya512** [comment]
Yes, I tried many times,not work now!

**Comment by Hornobster** [comment]
News on this?

**Comment by phynet** [comment]
Sorry, but no :(

**Comment by sallyahmed** [comment]
any updates ?

**Comment by phynet** [comment]
Still the same....I would love if someone else find something, because I couldn't

**Comment by sridharreddy123** [comment]
Hi Team, Any update on this? IOS 11 not working :( Please let us know the update on this. 
Thank you!

**Comment by sachithamh** [comment]
any updates on this ???

**Comment by jason1813** [comment]
What about an update now ;)
